name: Test R Script with Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # The GitHub Actions runner will be based on Ubuntu
    
      services:
        selenium:
          image: selenium/standalone-chrome:latest
          options:  |
            --health-cmd="curl --silent --fail http://localhost:4444/wd/hub/status || exit 1"
            --health-timeout=90s   
            --health-retries=5    
            --health-interval=15s 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'  # You can change this to any specific R version you want

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev curl
        sudo apt-get install -y default-jdk  # Install Java Development Kit (JDK)
        R -e "install.packages('RSelenium')"
    
    - name: Wait for Selenium to be ready
      run: |
        curl http://localhost:4444/wd/hub/status
        sleep 10  # Wait to ensure Selenium is ready

    - name: Run R script
      run: Rscript script.R
